
  get:
    description: This API is used for getting session                    
    responses: 
      200:
        description: Get Session  
        body: 
           application/json:
            example : {
              "ns0:createsessionResponse" : {
                "@xmlns:ns0" : "urn:UMARKETSCWS",
                "ns0:createsessionReturn" : {
                  "ns0:sessionid" : "SHKV9BY012K0IM449I3K",
                  "ns0:result" : 0,
                  "ns0:result_namespace" : "session"
                }
              }
            }
          
            
            
            
        
          
          
          
          
